{% set name = "connectorx" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/sfu-db/connector-x/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 512ce8b43c738d4f2fef460ef6b0de63f7959571d4d9c943425702d6ca3110f9

build:
  number: 1

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.0,<2.0                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - posix                               # [win]
    - cmake
    - make                                # [unix]
    - cargo-bundle-licenses
    - libclang                            # [unix]
    - clangdev                            # [unix]
  host:
    - python
    - pip
    - poetry
    - maturin >=1.0,<2.0
    - krb5                                # [linux]
    - openssl
    - zlib
  run:
    - python
    - numpy >=1.21.5

test:
  imports:
    - connectorx
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sfu-db/connector-x
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Fastest library to load data from DB to DataFrames in Rust and Python
  dev_url: https://github.com/sfu-db/connector-x

extra:
  recipe-maintainers:
    - '0xbe7a'
    - timkpaine
    - wangxiaoying
    - xhochy
